### ISSUE TITLE
Use SMS service

### ISSUE THREAD

**Issue by galulex** [geekhub-rails/avatron#6]
Twilio or SvitSMS

**Comment by lubo4kaTarasenko** [comment]
@galulex could you provide more details?
1. Integrate with `Twilio or SvitSMS`
2. Send 4-letter codes in SMS (?)
3. Implement code generation / confirmation / expiration (?)

**Comment by galulex** [comment]
> @galulex could you provide more details?
> 
> 1. Integrate with `Twilio or SvitSMS`
> 2. Send 4-letter codes in SMS (?)
> 3. Implement code generation / confirmation / expiration (?)

- Use SvitSMS
- We have code already generated in `UserPhone`
- Send SMS only in production environment
- For other environments stub one code `1111`
